/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Θοδωρης
 */
public class ERGASIA extends javax.swing.JFrame {

  
    public ERGASIA() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TABLE1 = new javax.swing.JButton();
        TABLE2 = new javax.swing.JButton();
        TABLE3 = new javax.swing.JButton();
        TABLE4 = new javax.swing.JButton();
        TABLE5 = new javax.swing.JButton();
        TABLE6 = new javax.swing.JButton();
        TABLE7 = new javax.swing.JButton();
        TABLE8 = new javax.swing.JButton();
        TABLE9 = new javax.swing.JButton();
        TABLE11 = new javax.swing.JButton();
        TABLE12 = new javax.swing.JButton();
        TABLE14 = new javax.swing.JButton();
        TABLE15 = new javax.swing.JButton();
        TABLE10 = new javax.swing.JButton();
        TABLE13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("ΤΡΑΠΕΖΙΑ");

        TABLE1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE1.setText("1");
        TABLE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE1ActionPerformed(evt);
            }
        });

        TABLE2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE2.setText("2");
        TABLE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE2ActionPerformed(evt);
            }
        });

        TABLE3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE3.setText("3");
        TABLE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE3ActionPerformed(evt);
            }
        });

        TABLE4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE4.setText("4");
        TABLE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE4ActionPerformed(evt);
            }
        });

        TABLE5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE5.setText("5");
        TABLE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE5ActionPerformed(evt);
            }
        });

        TABLE6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE6.setText("6");
        TABLE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE6ActionPerformed(evt);
            }
        });

        TABLE7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE7.setText("7");
        TABLE7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE7ActionPerformed(evt);
            }
        });

        TABLE8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE8.setText("8");
        TABLE8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE8ActionPerformed(evt);
            }
        });

        TABLE9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE9.setText("9");
        TABLE9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE9ActionPerformed(evt);
            }
        });

        TABLE11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE11.setText("11");
        TABLE11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE11ActionPerformed(evt);
            }
        });

        TABLE12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE12.setText("12");
        TABLE12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE12ActionPerformed(evt);
            }
        });

        TABLE14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE14.setText("14");
        TABLE14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE14ActionPerformed(evt);
            }
        });

        TABLE15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE15.setText("15");
        TABLE15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE15ActionPerformed(evt);
            }
        });

        TABLE10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE10.setText("10");
        TABLE10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE10ActionPerformed(evt);
            }
        });

        TABLE13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLE13.setText("13");
        TABLE13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLE13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TABLE1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TABLE2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TABLE3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TABLE7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TABLE8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TABLE9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TABLE13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TABLE10, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TABLE11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TABLE12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TABLE14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TABLE15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TABLE4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TABLE5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TABLE6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TABLE1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLE2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLE3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TABLE4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLE5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLE6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TABLE7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLE8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLE9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TABLE12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLE11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLE10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TABLE14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLE15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TABLE13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TABLE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE6ActionPerformed
      
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 6");
        EPILOGES.dataList6();
        EPILOGES.show_data6();
        dispose();
    }//GEN-LAST:event_TABLE6ActionPerformed

    private void TABLE7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE7ActionPerformed
      
      EPILOGES.setVisible(true);
      EPILOGES.setTitle("ΤΡΑΠΕΖΙ 7");
      EPILOGES.dataList7();
      EPILOGES.show_data7();
      dispose();
    }//GEN-LAST:event_TABLE7ActionPerformed

    private void TABLE8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE8ActionPerformed

        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 8");
        EPILOGES.dataList8();
        EPILOGES.show_data8();
        dispose();
    }//GEN-LAST:event_TABLE8ActionPerformed

    private void TABLE9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE9ActionPerformed
   
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 9");
        EPILOGES.dataList9();
        EPILOGES.show_data9();
        dispose();
    }//GEN-LAST:event_TABLE9ActionPerformed

    private void TABLE11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE11ActionPerformed

        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 11");
        EPILOGES.dataList11();
        EPILOGES.show_data11();
        dispose();
    }//GEN-LAST:event_TABLE11ActionPerformed

    private void TABLE12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE12ActionPerformed
      
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 12");
        EPILOGES.dataList12();
        EPILOGES.show_data12();
        dispose();
    }//GEN-LAST:event_TABLE12ActionPerformed

    private void TABLE14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE14ActionPerformed

        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 14");
        EPILOGES.dataList14();
        EPILOGES.show_data14();
        dispose();
    }//GEN-LAST:event_TABLE14ActionPerformed

    private void TABLE15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE15ActionPerformed
     
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 15");
        EPILOGES.dataList15();
        EPILOGES.show_data15();
        dispose();
    }//GEN-LAST:event_TABLE15ActionPerformed

    private void TABLE10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE10ActionPerformed
    
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 10");
        EPILOGES.dataList10();
        EPILOGES.show_data10();
        dispose();
    }//GEN-LAST:event_TABLE10ActionPerformed

    private void TABLE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE1ActionPerformed
 
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 1");
        EPILOGES.dataList();
        EPILOGES.show_data();
        dispose();
    }//GEN-LAST:event_TABLE1ActionPerformed

    private void TABLE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE2ActionPerformed
       
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 2");
        EPILOGES.dataList2();
        EPILOGES.show_data2();
        dispose();
    }//GEN-LAST:event_TABLE2ActionPerformed

    private void TABLE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE3ActionPerformed
        
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 3");
        EPILOGES.dataList3();
        EPILOGES.show_data3();
        dispose();
        
    }//GEN-LAST:event_TABLE3ActionPerformed

    private void TABLE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE4ActionPerformed
      
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 4");
        EPILOGES.dataList4();
        EPILOGES.show_data4();
        dispose();
    }//GEN-LAST:event_TABLE4ActionPerformed

    private void TABLE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE5ActionPerformed
      
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 5");
        EPILOGES.dataList5();
        EPILOGES.show_data5();
        dispose();
    }//GEN-LAST:event_TABLE5ActionPerformed

    private void TABLE13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLE13ActionPerformed
     
        EPILOGES.setVisible(true);
        EPILOGES.setTitle("ΤΡΑΠΕΖΙ 13");
       EPILOGES.dataList13();
        EPILOGES.show_data13();
        dispose();
    }//GEN-LAST:event_TABLE13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERGASIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERGASIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERGASIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERGASIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ERGASIA().setVisible(true);
               
            }
        });
    }
    EPILOGES EPILOGES= new EPILOGES();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TABLE1;
    private javax.swing.JButton TABLE10;
    private javax.swing.JButton TABLE11;
    private javax.swing.JButton TABLE12;
    private javax.swing.JButton TABLE13;
    private javax.swing.JButton TABLE14;
    private javax.swing.JButton TABLE15;
    private javax.swing.JButton TABLE2;
    private javax.swing.JButton TABLE3;
    private javax.swing.JButton TABLE4;
    private javax.swing.JButton TABLE5;
    private javax.swing.JButton TABLE6;
    private javax.swing.JButton TABLE7;
    private javax.swing.JButton TABLE8;
    private javax.swing.JButton TABLE9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
